### ISSUE TITLE
Done handler discussion

### ISSUE THREAD

**Issue by MauriceButler** [KoryNunn/kgo#8]
As discussed usage for new done handler

``` javascript
kgo
('thing', function(){
    done(true)
})
('foo', ['thing'], function(done){
    done(null, 'majigger');
})
('bar', ['foo'], function(foo, done){
    done(null, things)
})
.done(['foo'], callback)
```

The done handler gets passed error and / or the dependencies listed

**Comment by KoryNunn** [comment]
Also, .done() handler will not be called untill all tasks have completed, regardless of whether they are to be passed into the handler or not.

**Comment by KoryNunn** [comment]
Different idea:

```
kgo
('thing', function(){
    done(true)
})
('foo', ['thing'], function(done){
    done(null, 'majigger');
})
('bar', ['foo'], function(foo, done){
    done(null, things)
})
(['*error', 'foo'], callback)
```

where *error (or any arbitrary syntax) refers to the first error returned by any of the steps dependencies, or undefined of all dependencies succeeded.

**Comment by KoryNunn** [comment]
Implemented in v3
